### ISSUE TITLE
[FEAT] Compose file for Unifi + FerretDB

### ISSUE THREAD

**Issue by stevekerrison** [stevekerrison/uniferret#2]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Turn-key solution for combining a Unifi application with FerretDB's backends. Options could include:

- PostgreSQL backend
- SQLite backend
- Port forwarded unifi application
- Macvlan'd unifi application

### Reason for change

These are based on my use-cases and the available backends of FerretDB and will likely be adequate for others.

### Proposed code change

New compose files for these scenarios.

**Comment by stevekerrison** [comment]
Things to note:

- FerretDB docker expects database to be stored in `/state` for `sqlite`
- It expects database to be stored in `/var/lib/postgresql/data` for PostgreSQL

So these require different compose configurations, or some mangling.

**Comment by josephholsten** [comment]
Hey there, I'm having to update my unifi setup this week and will be attempting this. Yell at me if I don't check in by next week.

**Comment by stevekerrison** [comment]
Hi @josephholsten,

I somewhat gave up on this approach and switched to using newer [MongoDB with QEMU to overcome AVX(2) limitations](https://github.com/stevekerrison/mongo-qemu-avx). It's slow, but on a small deployment it doesn't matter.

However, for those who would like to fully de-couple from MongoDB, it would be interesting to see if this can still be made to work.

**Comment by josephholsten** [comment]
This is what I'm using:

```yaml
---
version: "2"
services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.104.0-ferretdb-2.3.1
    hostname: postgres
    environment:
      - POSTGRES_USER=unifi
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=postgres
    volumes:
      - ${CONFIG_DIR}/postgres/data:/var/lib/postgresql/data
    restart: on-failure

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.3.1
    hostname: ferretdb
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://unifi:${PASS}@postgres:5432/postgres
      - ${CONFIG_DIR}/ferret/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: on-failure

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=${PASS}
      - MONGO_HOST=ferretdb
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
    volumes:
      - ${CONFIG_DIR}/unifi-network-application/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped


networks:
  default:
      name: unifi
```

Seems like it just works.
